language: php
php:
  - "7.0"

before_install:
  - composer self-update

before_script:
  - composer require
  - composer install

script:
    - php ./src/taskrunner.php
    - php ./src/taskrunner.php --help
    - php ./src/taskrunner.php my