language: php
php:
  - "7.0"

before_install:
  - composer self-update

before_script:
  - composer require
  - composer install

script: php ./src/taskrunner.php
script: php ./src/taskrunner.php --help
script: php ./src/taskrunner.php my