language: php
php:
  - "7.0"

before_install:
  - composer self-update

before_script:
  - composer require
  - composer install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/EmailTest